version: '3'
services:
  linuxtests:
    image: microsoft/dotnet:2.0-sdk
    working_dir: /tests/linux
    volumes:
      - .:/tests/linux/
    command:
      - echo "(Start) linuxtests docker service"
      - echo "---"
      - ls
      - ls ./tests/
      - ls ./tests/linux
      - chmod a+x ./tests/linux/run.sh
      - ./tests/linux/run.sh
      - echo "---"
      - echo "(End) linuxtests docker service"
